### ISSUE TITLE
Am I using `external` incorrectly?

### ISSUE THREAD

**Issue by davestewart** [rollup/rollup-starter-lib#14]
Hello :)

> TLDR; I've used this project to bundle my plugin, but I can't seem to reference it in a demo project

I'm upgrading a project of mine, a Vue JS plugin called [VueSource](https://github.com/davestewart/vue-source) to use Rollup as the bundler.

I'm using this project as the starting point, as it seems the most likely candidate I've found to successfully create a module I can use in other projects, and publish to NPM.

The current branch for this upgrade is:

- https://github.com/davestewart/vue-source/tree/rollup

To make sure the plugin is robust before publishing, I generally host a demo project side-by-side with the plugin, using [Vue CLI](https://github.com/vuejs-templates/webpack-simple) to compile the web app and [NPM Link](https://docs.npmjs.com/cli/link) to see changes live as I update the plugin:

```
+- VueSource
    +- vue-source
    +- vue-source-demo
```

The current branch for this demo project is:

- https://github.com/davestewart/vue-source-demo

This setup has worked very successfully in other projects using Webpack.

However, although I've got the bundling, linking and compiling working, when the browser loads the demo webapp, the plugin is `undefined`:

![image](https://user-images.githubusercontent.com/132681/36067057-99f5d73e-0ead-11e8-8d68-747918d03168.png)

In the image above the `../vue-source` link seems curious to me, as I would have expected to have seen it in `node_modules` - where it actually is.

At first I thought this might be an NPM link problem, but now I am thinking this has more to do with Rollup's `external` option.

I confirmed this by adding a breakpoint to both files, and it seems that **both actually load** so I'm suspecting that the reason that the module is `undefined` has something to do with this, though I'm not sure.

Can anyone shed any light?

Thanks.

**Comment by eventualbuddha** [comment]
Closing as stale. This isn't really the best place to ask this sort of question, though I appreciate how thorough you were in detailing it. I hope you got it sorted out!
