### ISSUE TITLE
Should be `dist` commited?

### ISSUE THREAD

**Issue by langpavel** [rollup/rollup-starter-lib#8]
Hi, thanks for great kick in! but..

**I think that `dist` should be ignored from version control**, like `build` is excluded in many others projects.

I expected that there will be more opinions, but I did't found it there, no much opened issues, no debates.. so I'm trying kick up this with this one :slightly_smiling_face:

**Comment by eventualbuddha** [comment]
I agree. I’d merge a PR to add it to `.gitignore`.

**Comment by avdeev** [comment]
What about distribution through bower or CDN?

**Comment by eventualbuddha** [comment]
I would have thought bowed effectively dead, since it’s been [deprecated for around 7 months](https://github.com/bower/bower/issues/2298). And you can use unpkg for CDN functionality.

**Comment by Grsmto** [comment]
I disagree with this. I think a lot of users still uses libraries by simply downloading the zip file from Github. If you gitignore the dist folder, they won't be able to do this anymore.
Also ignoring the dist file doesn't really add any value here (it's not like you want to save space in Github's HD or anything).

**Comment by langpavel** [comment]
@Grsmto I cannot agree. Readable diffs are more important for code review workflow

**Comment by eventualbuddha** [comment]
> I think a lot of users still uses libraries by simply downloading the zip file from Github.

For users who want to provide that, they can by all means do so. However, for the vast majority of users simply creating versions appropriate to the target and putting them in `dist` and publishing that to npm will enable downloading files for use in a project as you say or referencing them directly by using unpkg. For example, http://unpkg.com/lgtm@latest/dist/lgtm.js.

> Also ignoring the dist file doesn't really add any value here.

@langpavel is correct: readable diffs are more important than the marginal utility of having `dist` checked into git. On top of that, you now have to make sure that the `dist` build properly matches the source files. This is a tedious and error-prone process, which would be best automated away if it weren't better to simply omit `dist` from git.

My own projects used to have the built version checked into `dist` for exactly the reasons you gave, but years of experience of the pain it causes plus the fall of bower and the rise of tools like unpkg have made it clear that checking build files into git is not currently the best approach for npm packages, or likely any software system with build artifacts.

**Comment by avdeev** [comment]
How i can create demo page for unpublished to NPM version of my lib?
CDN work only with published versions.

**Comment by eventualbuddha** [comment]
Lots of ways:
* commit a built version to the `gh-pages` branch as part of a demo website
* publish pre-release versions that can be accessed through unpkg by e.g. a `beta` tag
* build and push to a static site host like now.sh or surge.sh
* use a separate repository whose sole purpose is to contain built versions of your package (i.e. the whole of https://github.com/components)

There’s no shortage of good options.

**Comment by langpavel** [comment]
Nice, thanks!
